name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and build server dependencies
        working-directory: Project/server
        run: |
          npm  install 
          node server.js
          npm ci
          # Optionally, you can run server build commands here if needed
          # For example: npm run build

      - name: Install and build client dependencies
        working-directory: Project/client
        run: |
          npm ci
          # Optionally, you can run client build commands here if needed
          # For example: npm run build

      - name: Run tests
        working-directory: Project
        run: |
          # If your tests are located in the server or client directories,
          # specify the appropriate test commands here.
          # Example:
          # npm test --prefix server
          # npm test --prefix client

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        
